import { type OxlintConfig } from 'oxlint'

export const config: OxlintConfig = {
  categories: {
    correctness: 'warn',
    perf: 'warn',
    suspicious: 'warn',
  },
  ignorePatterns: ['dist'],
  jsPlugins: [
    {
      name: 'perfectionist',
      specifier: 'eslint-plugin-perfectionist',
    },
  ],
  options: {
    typeAware: true,
    typeCheck: true,
  },
  plugins: ['typescript', 'unicorn', 'oxc', 'import'],
  rules: {
    'array-callback-return': 'warn',
    'button-has-type': 'warn',
    'constructor-super': 'warn',
    curly: ['warn', 'all'],
    'default-case-last': 'warn',
    eqeqeq: ['warn', 'always', { null: 'ignore' }],
    'for-direction': 'warn',
    'func-style': ['warn', 'expression'],
    'getter-return': 'warn',
    'import/consistent-type-specifier-style': ['warn', 'prefer-inline'],
    'import/no-absolute-path': 'warn',
    'import/no-duplicates': 'warn',
    'import/unambiguous': 'warn',
    'no-alert': 'warn',
    'no-async-promise-executor': 'warn',
    'no-bitwise': 'warn',
    'no-compare-neg-zero': 'warn',
    'no-cond-assign': 'warn',
    'no-constant-condition': 'warn',
    'no-debugger': 'warn',
    'no-dupe-class-members': 'warn',
    'no-duplicate-imports': 'warn',
    'no-else-return': 'warn',
    'no-eval': 'warn',
    'no-fallthrough': 'warn',
    'no-implied-eval': 'warn',
    'no-new-func': 'warn',
    'no-object-constructor': 'warn',
    'no-promise-executor-return': 'warn',
    'no-redeclare': 'warn',
    'no-script-url': 'warn',
    'no-shadow': 'warn',
    'no-unsafe-negation': 'warn',
    'no-unsafe-return': 'warn',
    'no-unused-expressions': 'warn',
    'no-useless-rename': 'warn',
    'no-var': 'warn',
    'object-shorthand': 'warn',
    'perfectionist/sort-array-includes': 'warn',
    'perfectionist/sort-arrays': 'warn',
    'perfectionist/sort-classes': 'warn',
    'perfectionist/sort-decorators': 'warn',
    'perfectionist/sort-enums': 'warn',
    'perfectionist/sort-export-attributes': 'warn',
    'perfectionist/sort-exports': 'warn',
    'perfectionist/sort-heritage-clauses': 'warn',
    'perfectionist/sort-import-attributes': 'warn',
    // handled by oxfmt
    'perfectionist/sort-imports': 'off',
    'perfectionist/sort-interfaces': [
      'warn',
      {
        groups: [
          'index-signature',
          'required-property',
          'optional-property',
          'method',
        ],
        order: 'asc',
        type: 'alphabetical',
      },
    ],
    'perfectionist/sort-intersection-types': [
      'warn',
      { groups: ['keyword', 'unknown', 'nullish'] },
    ],
    'perfectionist/sort-jsx-props': 'warn',
    'perfectionist/sort-maps': 'warn',
    'perfectionist/sort-modules': 'warn',
    'perfectionist/sort-named-exports': 'warn',
    'perfectionist/sort-named-imports': 'warn',
    'perfectionist/sort-object-types': [
      'warn',
      {
        groups: [
          'index-signature',
          'required-property',
          'optional-property',
          'method',
        ],
        order: 'asc',
        type: 'alphabetical',
      },
    ],
    'perfectionist/sort-objects': [
      'warn',
      {
        groups: ['property', 'method'],
        order: 'asc',
        type: 'alphabetical',
      },
    ],
    'perfectionist/sort-sets': 'warn',
    'perfectionist/sort-switch-case': 'warn',
    'perfectionist/sort-union-types': [
      'warn',
      { groups: ['keyword', 'unknown', 'nullish'] },
    ],
    'perfectionist/sort-variable-declarations': 'warn',
    'prefer-arrow-callback': 'warn',
    'prefer-const': 'warn',
    'prefer-nullish-coalescing': 'warn',
    'prefer-optional-chain': 'warn',
    'prefer-promise-reject-errors': 'warn',
    'prefer-template': 'warn',
    'typescript/array-type': [
      'warn',
      { default: 'generic', readonly: 'generic' },
    ],
    'typescript/ban-types': 'warn',
    'typescript/consistent-type-definitions': ['warn', 'type'],
    'typescript/consistent-type-imports': [
      'warn',
      { fixStyle: 'inline-type-imports' },
    ],
    'typescript/no-namespace': 'warn',
    'typescript/no-non-null-asserted-nullish-coalescing': 'warn',
    'typescript/no-require-imports': 'warn',
    'typescript/no-unused-vars': 'warn',
    'typescript/prefer-for-of': 'warn',
    'typescript/prefer-literal-enum-member': 'warn',
    'typescript/prefer-nullish-coalescing': 'warn',
    'typescript/prefer-optional-chain': 'warn',
    'unicorn/consistent-date-clone': 'warn',
    'unicorn/consistent-existence-index-check': 'warn',
    'unicorn/consistent-function-scoping': 'warn',
    'unicorn/custom-error-definition': 'warn',
    'unicorn/error-message': 'warn',
    'unicorn/escape-case': 'warn',
    'unicorn/explicit-length-check': 'warn',
    'unicorn/new-for-builtins': 'warn',
    'unicorn/no-array-method-this-argument': 'warn',
    'unicorn/no-console-spaces': 'warn',
    'unicorn/no-hex-escape': 'warn',
    'unicorn/no-instanceof-array': 'warn',
    'unicorn/no-lonely-if': 'warn',
    'unicorn/no-new-buffer': 'warn',
    'unicorn/no-unreadable-array-destructuring': 'warn',
    'unicorn/no-unreadable-iife': 'warn',
    'unicorn/no-useless-undefined': 'warn',
    'unicorn/no-zero-fractions': 'warn',
    'unicorn/numeric-separators-style': 'warn',
    'unicorn/prefer-add-event-listener': 'warn',
    'unicorn/prefer-array-find': 'warn',
    'unicorn/prefer-array-flat': 'warn',
    'unicorn/prefer-array-flat-map': 'warn',
    'unicorn/prefer-array-index-of': 'warn',
    'unicorn/prefer-array-some': 'warn',
    'unicorn/prefer-date-now': 'warn',
    'unicorn/prefer-default-parameters': 'warn',
    'unicorn/prefer-includes': 'warn',
    'unicorn/prefer-math-min-max': 'warn',
    'unicorn/prefer-math-trunc': 'warn',
    'unicorn/prefer-modern-dom-apis': 'warn',
    'unicorn/prefer-negative-index': 'warn',
    'unicorn/prefer-node-protocol': 'warn',
    'unicorn/prefer-number-properties': 'warn',
    'unicorn/prefer-optional-catch-binding': 'warn',
    'unicorn/prefer-prototype-methods': 'warn',
    'unicorn/prefer-reflect-apply': 'warn',
    'unicorn/prefer-regexp-test': 'warn',
    'unicorn/prefer-spread': 'warn',
    'unicorn/prefer-string-replace-all': 'warn',
    'unicorn/prefer-string-slice': 'warn',
    'unicorn/prefer-string-starts-ends-with': 'warn',
    'unicorn/prefer-string-trim-start-end': 'warn',
    // for some reason forcing ternary operator on statements
    'unicorn/prefer-ternary': 'off',
    'unicorn/prefer-type-error': 'warn',
    'unicorn/switch-case-braces': ['warn', 'always'],
    'unicorn/throw-new-error': 'warn',
    yoda: 'warn',
  },
}

export default config
